[package]
name = "rust_tracer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lodepng = "3.4"
indicatif = "0.16.2"
rand = "0.8.4"
crossbeam-channel = "0.5"
rgb = "0.8"